### ISSUE TITLE
App Level - [ SLAM ]

### ISSUE THREAD

**Issue by JXproject** [TableUV/TableUV#10]
## Sub-tickets (Stage 1):
- [ ] EKF (localization) : https://github.com/TableUV/FYDP__TableUV/issues/45
- [x] Mapping : https://github.com/TableUV/FYDP__TableUV/issues/47
- [x] Basic Path (Motion) Planning : https://github.com/TableUV/FYDP__TableUV/issues/47

## Sub-tickets (Stage 2):
- [ ] EKF (localization) : https://github.com/TableUV/FYDP__TableUV/issues/45
- [ ] Mapping (reopen) : https://github.com/TableUV/FYDP__TableUV/issues/47
- [ ] Path (Motion) Planning : https://github.com/TableUV/FYDP__TableUV/issues/48

**Comment by JXproject** [comment]
Created sub-issue: https://github.com/TableUV/FYDP__TableUV/issues/45
